export enum SpendingCategoryTypeEnum {
  Bills = 'Bills',
  Dining = 'Dining',
  Entertainment = 'Entertainment',
  Fuel = 'Fuel',
  Gift = 'Gift',
  Grocery = 'Grocery',
  Health = 'Health',
  Invest = 'Invest',
  Other = 'Other',
  Shopping = 'Shopping',
  Subscriptions = 'Subscriptions',
  Travel = 'Travel',
  Custom = 'Custom',
}
